"use client";

function compactActionHash(value) {
  if (!value) return "";
  const text = String(value);
  return text.length > 14 ? `${text.slice(0, 7)}...${text.slice(-5)}` : text;
}

function generationSourceLabel(value) {
  const labels = {
    openai: "Generated by server AI model",
    deterministic_fallback_no_key: "Fallback draft - backend AI key not configured",
    fallback_after_model_error: "Fallback draft - model request failed",
  };
  return labels[value] || value || "";
}

function aiReviewDetailRows(action = {}) {
  const payload = action.draft_payload || {};
  if (!["draft_ai_review", "draft_ai_comment", "draft_ai_post"].includes(action.action_type)) return [];
  const prefs = payload.autonomy_preferences && typeof payload.autonomy_preferences === "object" ? payload.autonomy_preferences : {};
  const actorName = payload.ai_actor_display_name || payload.display_name || payload.actor || payload.ai_actor_username;
  return [
    actorName && ["AI delegate", actorName],
    payload.custody_label && ["Custody", payload.custody_label],
    payload.intended_choice && ["Intended vote", payload.intended_choice],
    payload.model_identity && ["Model/policy", payload.model_identity],
    payload.generation_source && ["Generation", generationSourceLabel(payload.generation_source)],
    payload.content_hash && ["Content hash", compactActionHash(payload.content_hash)],
    payload.reasoning_hash && ["Reasoning hash", compactActionHash(payload.reasoning_hash)],
    (action.action_type === "draft_ai_comment" || action.action_type === "draft_ai_post") && prefs.posts && ["Autonomy", "AI-authored content requires custodian approval"],
    action.action_type === "draft_ai_review" && prefs.reviews && ["Autonomy", prefs.reviews === "custodian_approval_required" ? "reviews require custodian approval" : prefs.reviews],
  ].filter(Boolean);
}

export function assistantAiActionConfidenceLabel(action = {}) {
  const value = action?.draft_payload?.confidence;
  if (value === null || value === undefined || value === "") return "";
  const number = Number(value);
  if (!Number.isFinite(number)) return "";
  return `${Math.round(Math.max(0, Math.min(number, 1)) * 100)}% confidence`;
}

export default function AssistantAiActionDetails({ action = {} }) {
  const isAiReviewDraft = action.action_type === "draft_ai_review";
  const isAiCommentDraft = action.action_type === "draft_ai_comment";
  const isAiPostDraft = action.action_type === "draft_ai_post";
  const isAiAuthoredDraft = isAiReviewDraft || isAiCommentDraft || isAiPostDraft;
  const aiReviewRows = aiReviewDetailRows(action);

  if (!isAiAuthoredDraft) return null;

  return (
    <div className="mt-2 rounded-[0.7rem] border border-[var(--pink)]/20 bg-[var(--pink)]/8 px-2.5 py-2">
      <p className="text-[0.68rem] font-semibold leading-5 text-[var(--text-gray-light)]">
        {isAiReviewDraft
          ? "Approval publishes exactly one AI vote and one rationale comment."
          : isAiPostDraft
          ? "Approval publishes exactly one AI-authored post."
          : "Approval publishes exactly one AI-authored comment."}
      </p>
      {aiReviewRows.length > 0 && (
        <div className="mt-2 grid gap-1 text-[0.66rem] leading-4 text-[var(--text-gray-light)]">
          {aiReviewRows.map(([label, value]) => (
            <p key={label}>
              <span className="font-semibold text-[var(--text-black)]">{label}:</span> {value}
            </p>
          ))}
        </div>
      )}
    </div>
  );
}
